// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKtVX1H29FrfRKaDK4syaXX9ejs8QO4fU',
    appId: '1:931471609537:web:f66c283f86de13b4cd0e40',
    messagingSenderId: '931471609537',
    projectId: 'notify-4c3d6',
    authDomain: 'notify-4c3d6.firebaseapp.com',
    storageBucket: 'notify-4c3d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8zuWDomJAyYB_f9zYXYzn2XHz7u8ukg',
    appId: '1:931471609537:android:eac79ebc93442ccfcd0e40',
    messagingSenderId: '931471609537',
    projectId: 'notify-4c3d6',
    storageBucket: 'notify-4c3d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqa2v63XBlYX9F15wWdgTKLNOGECPLEhg',
    appId: '1:931471609537:ios:06528013dbfb3bc4cd0e40',
    messagingSenderId: '931471609537',
    projectId: 'notify-4c3d6',
    storageBucket: 'notify-4c3d6.appspot.com',
    iosBundleId: 'com.example.notifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqa2v63XBlYX9F15wWdgTKLNOGECPLEhg',
    appId: '1:931471609537:ios:b56b66af0615e0c6cd0e40',
    messagingSenderId: '931471609537',
    projectId: 'notify-4c3d6',
    storageBucket: 'notify-4c3d6.appspot.com',
    iosBundleId: 'com.example.notifyFlutter.RunnerTests',
  );
}
